### ISSUE TITLE
Can we add "color map" in torchshow?

### ISSUE THREAD

**Issue by Disciple7** [xwying/torchshow#18]
I'm visualizing my feature map using torchshow. It's very useful to me. However, torchshow only support grap color map when visualizing tensor whose shape is (N, C, H, W), where C>=1. I need color map like cv2.COLORMAP_JET to show clear information about feature tensors, which will make things easier, thanks!

**Comment by xwying** [comment]
Glad to hear that TorchShow is helpful! For your question, can you try if the [`cmap`](https://github.com/xwying/torchshow/blob/master/API.md) parameter works? This option accepts [matplotlib colormap](https://matplotlib.org/stable/tutorials/colors/colormaps.html) so you may need to find if there is one equivalent to `cv2.COLORMAP_JET` there, or you could potentially construct one to fit your need.

**Comment by xwying** [comment]
I did a quick testing using the following code and the results look good. So I'll close this issue for now. Please feel free to reopen the issue if this function is not working for your case.

```python
a = np.random.rand(1, 8, 100, 100)
ts.show(a[0], cmap='jet')
```
