### ISSUE TITLE
Plot titles

### ISSUE THREAD

**Issue by alexinnovap** [xwying/torchshow#21]
Hi there, I am currently visualising feature maps in yolov7 for each layer and I was wondering if it was possible for each image to have a subtitle? for example "Feature map 1"
![filter_maps](https://github.com/xwying/torchshow/assets/137399425/27d4135a-b0da-42bb-b693-78aa28780e62)

**Comment by xwying** [comment]
Yes, you could do it by using the `axes_title` option. For example:

```python
ts.show(feature_map, axes_title="Feature Map {img_id_from_1}")
```
