### ISSUE TITLE
Key error - axes.titlecolor

### ISSUE THREAD

**Issue by SM1991CODES** [xwying/torchshow#22]
Hi,
I get this error when I try to import torchshow

![image](https://github.com/xwying/torchshow/assets/69435296/36529496-ada8-4058-b3c0-5479ac1fbcb4)

**Comment by xwying** [comment]
Hi, it seems that it might be caused by the matplotlib version. However, I tried several matplotlib version but was not able to reproduce this error on my side. Could you let me know which matplotlib version you are using?

**Comment by xwying** [comment]
The latest commit https://github.com/xwying/torchshow/commit/e728c9d4ac1acaa92190175912700ac86f85117a should fix this issue by removing some unnecessary lines. It will be put into the next release. Right now you could install from the master branch to see if it resolves the issue.

```
pip install git+https://github.com/xwying/torchshow.git@master
```

**Comment by SM1991CODES** [comment]
Thanks for the update.
I can confirm this now works with both BCHW and BHWC format tensors.
![image](https://github.com/xwying/torchshow/assets/69435296/7c45130b-68b4-4b2e-a09f-62fdf0a8112a)

![image](https://github.com/xwying/torchshow/assets/69435296/71ba7bc7-a3ba-44d2-b6ba-7469f1f92614)

**Comment by xwying** [comment]
Thanks for the confirmation. Glad to hear that the tool is helpful for your project!
