### ISSUE TITLE
torchshow.save memory problem

### ISSUE THREAD

**Issue by Z-MU-Z** [xwying/torchshow#6]
Hi, i meet this warning when i use torchshow to save masks in 'for' loop. Is there anyway to solve  this problem?

envs/py38/lib/python3.8/site-packages/torchshow/visualization.py:108: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, axes = plt.subplots(nrows=nrows, ncols=ncols, squeeze=False)

**Comment by xwying** [comment]
Hi, it seems like you are using an older version of torchshow. Can you try to install the new version and see if it resolve the problem?

**Comment by Z-MU-Z** [comment]
Thanks a lot! it works!
